import { ArrowUpRight } from "lucide-react";
import { Brand } from "@/components/site-header";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { services } from "@/lib/content";
import { DemoContact } from "@/components/demo-contact";
export function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow">{children}</div>}
export function FAQ({items}:{items:{question:string;answer:string}[]}){return <Accordion type="single" collapsible className="faq">{items.map((f,i)=><AccordionItem key={f.question} value={`faq-${i}`}><AccordionTrigger>{f.question}</AccordionTrigger><AccordionContent forceMount>{f.answer}</AccordionContent></AccordionItem>)}</Accordion>}
export function CTA(){return <section className="cta-section"><div className="container cta-layout"><div><Eyebrow>Your next good idea starts here</Eyebrow><h2>READY? <span>LET’S PLAY.</span></h2><p>Tell us about your space, your event or the machine you have in mind.</p></div><a className="button button-dark" href="/contact">Start a conversation <ArrowUpRight size={19}/></a></div></section>}
export function Footer(){return <footer className="site-footer"><div className="container"><div className="footer-top"><div className="footer-intro"><Brand/><p>Bringing a little more play to venues,<br/>events and spaces across Sydney & NSW.</p><a href="/contact" className="text-link light">Let’s make something fun happen <ArrowUpRight size={16}/></a></div><div><h2>FIND YOUR FUN</h2>{services.map(s=><a key={s.slug} href={`/${s.slug}`}>{s.shortTitle}</a>)}</div><div><h2>GET TO KNOW US</h2><a href="/about">About us</a><a href="/service-areas">Service areas</a><a href="/contact">Contact & quotes</a><a href="/guides">Guides & checklists</a><a href="/privacy">Privacy</a></div></div><DemoContact compact/><div className="footer-bottom"><span>© {new Date().getFullYear()} Arcade Game Australia</span><span>Made for good times.</span><img className="footer-mark" src="/arcade-icon.svg" width={24} height={24} alt="" aria-hidden="true" loading="lazy"/></div></div></footer>}
